version: 0.0
os: linux
files:
  - source: /
    destination: /
    overwrite: yes
hooks:
  beforeinstall:
    - location: scripts/before_install.sh
      runas: root
      timeout: 300
  Applicationstop:
    - location: scripts/application_stop.sh
      runas: root
      timeout: 300
ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
      timeout: 60